# MPCHandler

In [1]:
from spacerocks import MPCHandler
from spacerocks import SpiceKernel
import pandas as pd

kernel = SpiceKernel.defaults()

Using default configuration:
  Kernel paths: ["/Users/kjnapier/.spacerocks/spice"]
  Download directory: "/Users/kjnapier/.spacerocks/spice"
  Auto-download: true

Processing kernel: latest_leapseconds.tls
✓ Found existing kernel at: /Users/kjnapier/.spacerocks/spice/latest_leapseconds.tls
Loading kernel: /Users/kjnapier/.spacerocks/spice/latest_leapseconds.tls

Processing kernel: de440s.bsp
✓ Found existing kernel at: /Users/kjnapier/.spacerocks/spice/de440s.bsp
Loading kernel: /Users/kjnapier/.spacerocks/spice/de440s.bsp

Processing kernel: earth_1962_240827_2124_combined.bpc
➜ Downloading kernel...
    Downloading from https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_1962_240827_2124_combined.bpc
    Saving to /Users/kjnapier/.spacerocks/spice/earth_1962_240827_2124_combined.bpc
Loading kernel: /Users/kjnapier/.spacerocks/spice/earth_1962_240827_2124_combined.bpc

Processing kernel: codes_300ast_20100725.bsp
✓ Found existing kernel at: /Users/kjnapier/.spacerocks/spice/codes_300ast_20100725.bsp
Loading kernel: /Users/kjnapier/.spacerocks/spice/codes_300ast_20100725.bsp

Processing kernel: codes_300ast_20100725.tf
✓ Found existing kernel at: /Users/kjnapier/.spacerocks/spice/codes_300ast_20100725.tf
Loading kernel: /Users/kjnapier/.spacerocks/spice/codes_300ast_20100725.tf

In [2]:
# Create a new MPCHandler object and pass the path to the data directory where the MPC data files are stored
# The path can be specified as shown below, or if left blank, it will default to and make "~/.spacerocks/mpc" in your home directory
"""
mpc_data_path = "data/mpc"
handler = MPCHandler(mpc_data_path)
"""

handler = MPCHandler()

In [3]:
from spacerocks.observing import Observatory

In [4]:
from spacerocks.time import Time

In [5]:
handler.get_detections("2015 BP519", formats=["ADES_DF"])

Request Data: {"desigs": ["2015 BP519"], "output_format": ["ADES_DF"]}

RuntimeError: builder error: unsupported value

In [ ]:
2

In [ ]:
response = handler.get_detections("2015 BP519", formats=["ADES_DF"])

In [ ]:
response[1]

200

In [ ]:
# You can also get all the detection data from the MPC for a specific object by passing its name with get_detections and the format(s) you want the data in 
# (ADES is the current MPC standard and default. Options are "ADES_DF", "OBS_DF", "XML".)

# If ADES is specified, get_detections will return a tuple with Observation objects and the raw data in the specified format(s)
observations, response = handler.get_detections("holman", formats=["ADES_DF", "OBS_DF", "XML"])
if response:
    ades_df = pd.DataFrame(response[0]['ADES_DF'])
    obs_df = pd.DataFrame(response[0]['OBS_DF'])
    xml_string = response[0]['XML']

In [3]:
# Create a dataframe of all the Near-Earth Asteroids (NEAs) from the MPC data files
nea_df = handler.fetch_data(
    catalog="nea_extended", # https://minorplanetcenter.net/data details available catalogs
    orbit_type=None,  # None means get all types, and is the default
    storage_format="json",  # Options: "feather", "json", None: Default is "feather", None will get the data directly from the MPC without saving it locally
    output_format="dataframe" # Options: "dataframe", "rocks": Default is "dataframe", "rocks" returns a RockCollection 
)

# Available orbit_types:

# "Atira",
# "Aten", 
# "Apollo",
# "Amor",
# "Hungaria",
# "MBA",
# "Phocaea",
# "Hilda",
# "Jupiter Trojan",
# "Distant Object"

Using existing feather file: /Users/kjnapier/.spacerocks/mpc/nea_extended.feather

In [4]:
nea_df.head()

,H,G,Epoch,M,Peri,Node,i,e,a,Principal_desig,orbit_type
0,10.41,0.15,2460600.5,86.66754,178.91030,304.27434,10.82773,0.222691,1.458181,A898 PA,Amor
1,15.59,0.15,2460600.5,148.45068,156.21553,183.85715,11.57526,0.546779,2.636157,A911 TB,Amor
2,13.79,0.15,2460600.5,340.19843,350.47423,110.42302,9.39880,0.571093,2.472525,A918 AA,Amor
3,9.18,0.15,2460600.5,6.98496,132.49616,215.49497,26.68673,0.532826,2.665299,A924 UB,Amor
4,17.37,0.15,2460600.5,271.70081,26.71763,171.26079,11.86848,0.434718,1.920154,1932 EA1,Amor

In [5]:
# Make a dataframe of all the Jupiter Trojans in the MPC and save it as a json 
jt_df = handler.fetch_data(
    catalog="mpcorb_extended",
    orbit_type="Jupiter Trojan",
    storage_format="json")

Using existing json file: /Users/kjnapier/.spacerocks/mpc/mpcorb_extended.json.gz

In [6]:
jt_df.head()

,H,G,Epoch,M,Peri,Node,i,e,a,Principal_desig,orbit_type
0,8.24,0.15,2460800.5,60.36916,134.10912,316.53701,10.31633,0.148409,5.213512,A906 DN,Jupiter Trojan
1,8.25,0.15,2460800.5,25.58996,308.67218,44.34998,22.06484,0.139533,5.206045,A906 UL,Jupiter Trojan
2,7.36,0.15,2460800.5,353.44419,180.17874,342.80319,18.14949,0.024155,5.275525,A907 CF,Jupiter Trojan
3,8.72,0.15,2460800.5,165.81094,343.83350,350.75732,4.52183,0.115690,5.170048,A908 FE,Jupiter Trojan
4,8.64,0.15,2460800.5,112.96468,337.54459,301.44227,8.89575,0.124047,5.208930,A917 SU,Jupiter Trojan

In [7]:
# Now if we want to access the 'mpcorb_extended' catalog again, it will search for the file 
# and load it from there, instead of downloading it again from the MPC

apollo_df = handler.fetch_data(
    catalog="mpcorb_extended",
    orbit_type="Apollo")

Using existing json file: /Users/kjnapier/.spacerocks/mpc/mpcorb_extended.json.gz

In [8]:
apollo_df.head()

,H,G,Epoch,M,Peri,Node,i,e,a,Principal_desig,orbit_type
0,16.55,0.15,2460800.5,336.97137,31.43599,87.95308,22.80382,0.826997,1.077994,1949 MA,Apollo
1,15.27,0.15,2460800.5,71.15106,277.00263,337.14861,13.33584,0.335638,1.245661,1951 RA,Apollo
2,14.28,0.15,2460800.5,319.46206,127.27860,274.20848,9.38190,0.436039,1.367884,1948 OA,Apollo
3,16.08,0.09,2460800.5,3.39936,286.02502,35.55706,6.35219,0.559847,1.470719,1932 HA,Apollo
4,15.46,0.15,2460800.5,231.67485,268.90180,345.68956,18.35872,0.606324,2.261088,1948 EA,Apollo

In [9]:
# We can also get the data in the form of a RockCollection object, either by passing the output_format parameter as "rocks" or by using the RockCollection class
from spacerocks import RockCollection

nea_rocks = RockCollection.from_mpc(
    catalog="nea_extended",
    download_data=False, # Set to True if you want to download the data from the MPC, default is False
    orbit_type=None, # None means get all types, and is the default 
)

trojan_rocks = handler.fetch_data(
    catalog="mpcorb_extended",
    orbit_type="Jupiter Trojan",
    output_format="rocks")

Using existing feather file: /Users/kjnapier/.spacerocks/mpc/nea_extended.feather
Using existing json file: /Users/kjnapier/.spacerocks/mpc/mpcorb_extended.json.gz

In [10]:
nea_rocks

RockCollection: 37460 rocks

In [11]:
nea_rocks[0]

SpaceRock: A898 PA
position: [[-0.847254164498476, -1.2219158379054114, -0.2655208256624848]]
velocity: [[0.009213129392774662, -0.010204668116499577, 0.00035698153637254363]]
epoch: 2460600.5 UTC JD
reference_plane: ECLIPJ2000
origin: SSB

In [12]:
print(nea_rocks[0].name)
print(nea_rocks[0].a())
print(nea_rocks[0].e())
print(nea_rocks[0].inc())
print(nea_rocks[0].node())
print(nea_rocks[0].arg())
print(nea_rocks[0].mean_anomaly())

A898 PA
1.4581813
0.22269060000000004
0.18897953901696607
5.310589062332683
3.122573800730802
1.512633927603887

In [13]:
trojan_rocks[0]

SpaceRock: A906 DN
position: [[-4.774241023880383, 1.131938294170256, -0.448246405473186]]
velocity: [[-0.0027554624094699894, -0.007356453239794933, -0.0013169337174983166]]
epoch: 2460800.5 UTC JD
reference_plane: ECLIPJ2000
origin: SSB

:

In [15]:
obs_df

                                                 obs80
0    K8117K00CB9J*1C2000 02 06.33316 10 00 19.67 +1...
1    K8117K00CB9J 1C2000 02 06.47280 10 00 11.68 +1...
2    K8117K00CB9J  C2000 02 14.27304 09 52 45.90 +1...
3    K8117K00CB9J  C2000 02 14.29472 09 52 44.58 +1...
4    K8117K00CB9J  C2000 02 14.31641 09 52 43.28 +1...
..                                                 ...
410  K8117         C2024 10 04.31815621 40 53.746-1...
411  K8117         C2024 12 25.07493822 33 16.960-0...
412  K8117         C2024 12 25.08055722 33 17.330-0...
413  K8117         C2024 12 25.08615722 33 17.788-0...
414  K8117         C2024 12 25.09176122 33 18.220-0...

[415 rows x 1 columns]

In [16]:
for line in obs_df.itertuples():
    print(line)

Pandas(Index=0, obs80='K8117K00CB9J*1C2000 02 06.33316 10 00 19.67 +13 29 06.7          19.4 R b6858695')
Pandas(Index=1, obs80='K8117K00CB9J 1C2000 02 06.47280 10 00 11.68 +13 29 26.2                 b6858695')
Pandas(Index=2, obs80='K8117K00CB9J  C2000 02 14.27304 09 52 45.90 +13 48 13.4          19.7 Vbb6858691')
Pandas(Index=3, obs80='K8117K00CB9J  C2000 02 14.29472 09 52 44.58 +13 48 16.8          19.3 Vbb6858691')
Pandas(Index=4, obs80='K8117K00CB9J  C2000 02 14.31641 09 52 43.28 +13 48 19.8          19.3 Vbb6858691')
Pandas(Index=5, obs80='K8117K00CB9J  C2000 03 12.23606 09 29 45.54 +14 32 09.5          20.7 Vbi2624691')
Pandas(Index=6, obs80='K8117K00CB9J  C2000 03 12.26274 09 29 44.50 +14 32 10.8          19.8 Vbi2624691')
Pandas(Index=7, obs80='K8117K00CB9J  C2000 03 12.28917 09 29 43.46 +14 32 11.8          19.8 Vbi2624691')
Pandas(Index=8, obs80='K8117K00CB9J  C2002 09 05.29300023 29 50.754+00 31 03.30         20.16Veh9647645')
Pandas(Index=9, obs80='K8117K00CB9J  C2002 09 05.29647223 29 50.568+00 31 02.72         20.83 eh9647645')
Pandas(Index=10, obs80='K8117K02S61W* C2002 09 17.12981 23 19 25.07 -00 06 24.1          20.6  cg3799644')
Pandas(Index=11, obs80='K8117K02S61W  C2002 09 17.20186 23 19 21.16 -00 06 39.0          19.9  cg3799644')
Pandas(Index=12, obs80='K8117K02S61W  C2002 09 17.26510 23 19 17.71 -00 06 51.8          20.0  cg3799644')
Pandas(Index=13, obs80='K8117K02S61W  C2002 09 18.20027 23 18 28.56 -00 10 02.0          20.9  cg3799644')
Pandas(Index=14, obs80='K8117K02S61W  C2002 09 18.27293 23 18 24.65 -00 10 17.2          20.2  cg3799644')
Pandas(Index=15, obs80='K8117K02S61W  C2002 09 18.33556 23 18 21.27 -00 10 30.4          20.2  cg3799644')
Pandas(Index=16, obs80='K8117K00CB9J  C2002 10 05.27142023 05 00.165-01 05 38.43         20.54Veh9647645')
Pandas(Index=17, obs80='K8117K00CB9J  C2002 10 05.27489223 05 00.017-01 05 39.00         21.24 eh9647645')
Pandas(Index=18, obs80='K8117K00CB9J  C2003 12 28.27235 06 35 01.34 +31 40 06.0          19.6  cj5689704')
Pandas(Index=19, obs80='K8117K00CB9J  C2003 12 28.28536 06 35 00.56 +31 40 05.4          20.3  cj5689704')
Pandas(Index=20, obs80='K8117K00CB9J  C2003 12 28.29836 06 34 59.55 +31 40 04.8          19.9  cj5689704')
Pandas(Index=21, obs80='K8117K00CB9J  C2003 12 28.31153 06 34 58.68 +31 40 04.4          19.6  cj5689704')
Pandas(Index=22, obs80='K8117K00CB9J  C2003 12 28.32497 06 34 57.76 +31 40 04.0          19.9  cj5689704')
Pandas(Index=23, obs80='K8117K00CB9J  C2007 11 02.45145 03 03 40.17 +27 53 32.4          20.9 Vrw4577703')
Pandas(Index=24, obs80='K8117K00CB9J  C2007 11 02.45796 03 03 39.85 +27 53 31.2          20.1 Vrw4577703')
Pandas(Index=25, obs80='K8117K00CB9J  C2007 11 02.46448 03 03 39.52 +27 53 30.7          19.8 Vrw4577703')
Pandas(Index=26, obs80='K8117K00CB9J  C2007 11 02.47112 03 03 39.13 +27 53 27.7          19.8 Vrw4577703')
Pandas(Index=27, obs80='K8117K00CB9J  C2007 11 08.25699 02 57 54.51 +27 37 48.1          19.4  cw4577704')
Pandas(Index=28, obs80='K8117K00CB9J  C2007 11 08.26931 02 57 53.75 +27 37 45.4          19.7  cw4577704')
Pandas(Index=29, obs80='K8117K00CB9J  C2007 11 08.28171 02 57 53.09 +27 37 43.0          20.0  cw4577704')
Pandas(Index=30, obs80='K8117K00CB9J  C2007 11 08.29424 02 57 52.11 +27 37 40.3          20.0  cw4577704')
Pandas(Index=31, obs80='K8117K00CB9J  C2007 11 08.30673 02 57 51.40 +27 37 38.7          19.9  cw4577704')
Pandas(Index=32, obs80='K8117K00CB9J  C2007 11 20.15931 02 46 12.54 +26 51 30.8          19.8 Vrw8919G96')
Pandas(Index=33, obs80='K8117K00CB9J  C2007 11 20.16370 02 46 12.28 +26 51 29.5          19.8 Vrw8919G96')
Pandas(Index=34, obs80='K8117K00CB9J  C2007 11 20.16808 02 46 12.03 +26 51 28.3          19.5 Vrw8919G96')
Pandas(Index=35, obs80='K8117K00CB9J  C2007 11 20.17243 02 46 11.78 +26 51 27.4          19.7 Vrw8919G96')
Pandas(Index=36, obs80='K8117K00CB9J  C2007 12 16.19075 02 29 01.75 +24 48 30.0          20.6 Vrx1702G96')
Pandas(Index=37, obs80='K8117K00CB9J  C2007 12 16.19765 02 29 01.64 +24 48 28.5          20.3 Vrx1702G96')
Pandas(Index=38, obs80='K8117K00CB9J  C2007 12 16.20446 02 29 01.50 +24 48 26.7          20.4 Vrx1702G96')
Pandas(Index=39, obs80='K8117K00CB9J  C2007 12 16.21137 02 29 01.35 +24 48 24.7          20.6 Vrx1702G96')
Pandas(Index=40, obs80='K8117K00CB9J  C2008 01 01.15885 02 27 42.76 +23 54 05.5          21.0 Vr~03AWG96')
Pandas(Index=41, obs80='K8117K00CB9J  C2008 01 01.16729 02 27 42.80 +23 54 04.4          21.0 Vr~03AWG96')
Pandas(Index=42, obs80='K8117K00CB9J  C2008 01 01.17580 02 27 42.87 +23 54 02.7          21.0 Vr~03AWG96')
Pandas(Index=43, obs80='K8117K00CB9J  C2008 01 01.18436 02 27 42.91 +23 54 01.4          20.6 Vr~03AWG96')
Pandas(Index=44, obs80='K8117K00CB9J  C2009 01 18.38866 11 04 38.67 +06 02 47.0          20.6 Vr~03AWG96')
Pandas(Index=45, obs80='K8117K00CB9J  C2009 01 18.39384 11 04 38.60 +06 02 47.0          20.5 Vr~03AWG96')
Pandas(Index=46, obs80='K8117K00CB9J  C2009 01 18.39899 11 04 38.49 +06 02 46.6          20.9 Vr~03AWG96')
Pandas(Index=47, obs80='K8117K00CB9J  C2009 01 18.40413 11 04 38.38 +06 02 46.6          21.1 Vr~03AWG96')
Pandas(Index=48, obs80='K8117K00CB9J  C2009 02 13.25401 10 49 46.61 +06 25 19.5          20.0 Vo~04F8691')
Pandas(Index=49, obs80='K8117K00CB9J  C2009 02 13.27232 10 49 45.65 +06 25 21.7          20.7 Vo~04F8691')
Pandas(Index=50, obs80='K8117K00CB9J  C2009 02 13.29039 10 49 44.73 +06 25 24.1          20.5 Vo~04F8691')
Pandas(Index=51, obs80='K8117K00CB9J  C2009 02 21.25130 10 42 42.35 +06 45 35.5                o~04YT291')
Pandas(Index=52, obs80='K8117K00CB9J  C2009 02 21.25523 10 42 42.12 +06 45 36.1                o~04YT291')
Pandas(Index=53, obs80='K8117K00CB9J  C2009 02 21.25906 10 42 41.90 +06 45 36.8                o~04YT291')
Pandas(Index=54, obs80='K8117K00CB9J  C2009 02 26.28248 10 38 00.92 +06 59 47.7          19.5 Vr~04ow703')
Pandas(Index=55, obs80='K8117K00CB9J  C2009 02 26.29287 10 38 00.34 +06 59 49.4          19.8 Vr~04ow703')
Pandas(Index=56, obs80='K8117K00CB9J  C2009 02 26.30324 10 37 59.70 +06 59 51.3          19.4 Vr~04ow703')
Pandas(Index=57, obs80='K8117K00CB9J  C2009 02 26.31373 10 37 59.08 +06 59 52.7          19.9 Vr~04ow703')
Pandas(Index=58, obs80='K8117K00CB9J  C2009 02 27.33792 10 37 01.45 +07 02 49.9          19.5 Vr~04owG96')
Pandas(Index=59, obs80='K8117K00CB9J  C2009 02 27.34204 10 37 01.20 +07 02 50.5          19.1 Vr~04owG96')
Pandas(Index=60, obs80='K8117K00CB9J  C2009 02 27.34617 10 37 00.98 +07 02 51.2          19.7 Vr~04owG96')
Pandas(Index=61, obs80='K8117K00CB9J  C2009 02 27.35030 10 37 00.73 +07 02 52.1          19.7 Vr~04owG96')
Pandas(Index=62, obs80='K8117         C2009 03 26.25601 10 15 23.32 +08 06 35.6          20.3 Vr~05pcG96')
Pandas(Index=63, obs80='K8117         C2009 03 26.26423 10 15 23.00 +08 06 35.9          20.1 Vr~05pcG96')
Pandas(Index=64, obs80='K8117         C2009 03 26.27248 10 15 22.75 +08 06 36.6          20.3 Vr~05pcG96')
Pandas(Index=65, obs80='K8117         C2009 03 26.28064 10 15 22.42 +08 06 37.2          20.2 Vr~05pcG96')
Pandas(Index=66, obs80='K8117         C2011 07 03.42701 00 20 12.87 +04 13 45.8          21.4 Vr~0WunG96')
Pandas(Index=67, obs80='K8117         C2011 07 03.43280 00 20 13.09 +04 13 47.7          21.9 Vr~0WunG96')
Pandas(Index=68, obs80='K8117         C2011 07 03.43867 00 20 13.30 +04 13 50.6          21.2 Vr~0WunG96')
Pandas(Index=69, obs80='K8117         C2011 07 03.44446 00 20 13.56 +04 13 52.7          21.6 Vr~0WunG96')
Pandas(Index=70, obs80='K8117         C2011 09 29.14225 23 59 38.31 +06 18 42.7          20.3 Vo~0Yrb691')
Pandas(Index=71, obs80='K8117         C2011 09 29.16014 23 59 37.33 +06 18 38.7          20.5 Vo~0Yrb691')
Pandas(Index=72, obs80='K8117         C2011 09 29.17802 23 59 36.37 +06 18 34.9          20.4 Vo~0Yrb691')
Pandas(Index=73, obs80='K8117         C2011 10 28.20940 23 39 27.86 +04 35 19.3          20.2 Vr~0Zs1G96')
Pandas(Index=74, obs80='K8117         C2011 10 28.21454 23 39 27.72 +04 35 18.6          20.3 Vr~0Zs1G96')
Pandas(Index=75, obs80='K8117         C2011 10 28.21976 23 39 27.57 +04 35 17.3          20.2 Vr~0Zs1G96')
Pandas(Index=76, obs80='K8117         C2011 10 28.22497 23 39 27.43 +04 35 16.5          20.1 Vr~0Zs1G96')
Pandas(Index=77, obs80='K8117         C2012 12 07.41339 08 00 50.30 +27 46 53.8                o~0mK8691')
Pandas(Index=78, obs80='K8117         C2012 12 07.43165 08 00 49.80 +27 46 55.6                o~0mK8691')
Pandas(Index=79, obs80='K8117         C2012 12 07.44978 08 00 49.37 +27 46 57.1                o~0mK8691')
Pandas(Index=80, obs80='K8117         C2012 12 11.28655 07 59 04.05 +27 53 10.4          20.7 Vo~0mm5691')
Pandas(Index=81, obs80='K8117         C2012 12 11.28902 07 59 04.01 +27 53 10.3          20.4 Vo~0mm5691')
Pandas(Index=82, obs80='K8117         C2012 12 11.30424 07 59 03.52 +27 53 12.3          20.5 Vo~0mm5691')
Pandas(Index=83, obs80='K8117         C2012 12 11.30671 07 59 03.37 +27 53 12.4          20.5 Vo~0mm5691')
Pandas(Index=84, obs80='K8117         C2012 12 11.32196 07 59 02.86 +27 53 14.4          20.7 Vo~0mm5691')
Pandas(Index=85, obs80='K8117         C2012 12 11.32443 07 59 02.80 +27 53 14.8          20.6 Vo~0mm5691')
Pandas(Index=86, obs80='K8117         C2012 12 23.55517 07 50 34.212+28 13 53.01         20.1 wL~0n5ZF51')
Pandas(Index=87, obs80='K8117         C2012 12 23.56961 07 50 33.443+28 13 54.31         20.1 wL~0n5ZF51')
Pandas(Index=88, obs80='K8117         C2012 12 23.58407 07 50 32.681+28 13 55.58         20.1 wL~0n5ZF51')
Pandas(Index=89, obs80='K8117         C2012 12 23.59845 07 50 31.914+28 13 56.84         19.8 wL~0n5ZF51')
Pandas(Index=90, obs80='K8117         C2013 01 03.52273 07 40 05.381+28 28 13.03         19.8 rL~0nI0F51')
Pandas(Index=91, obs80='K8117         C2013 01 03.52946 07 40 04.940+28 28 13.38         19.8 iL~0nI0F51')
Pandas(Index=92, obs80='K8117         C2013 01 03.53277 07 40 04.725+28 28 13.52         19.9 iL~0nI0F51')
Pandas(Index=93, obs80='K8117         C2013 01 03.54248 07 40 04.105+28 28 14.03         19.8 iL~0nI0F51')
Pandas(Index=94, obs80='K8117         C2013 01 03.55567 07 40 03.250+28 28 14.63         19.6 iL~0nI0F51')
Pandas(Index=95, obs80='K8117         C2013 01 05.18345 07 38 21.38 +28 29 38.8          20.0 Vo~0nbl691')
Pandas(Index=96, obs80='K8117         C2013 01 05.20115 07 38 20.20 +28 29 39.6          20.0 Vo~0nbl691')
Pandas(Index=97, obs80='K8117         C2013 01 05.21884 07 38 18.98 +28 29 41.5          19.7 Vo~0nbl691')
Pandas(Index=98, obs80='K8117         C2013 01 15.26334 07 27 30.27 +28 32 52.6          20.0 Vr~0nxN703')
Pandas(Index=99, obs80='K8117         C2013 01 15.26944 07 27 29.73 +28 32 51.7          20.1 Vr~0nxN703')
Pandas(Index=100, obs80='K8117         C2013 01 15.27565 07 27 29.41 +28 32 53.4          20.0 Vr~0nxN703')
Pandas(Index=101, obs80='K8117         C2013 01 15.28189 07 27 28.94 +28 32 51.3          19.4 Vr~0nxN703')
Pandas(Index=102, obs80='K8117         C2013 05 11.25567 07 59 40.262+21 51 31.11         21.4 wL~0sDlF51')
Pandas(Index=103, obs80='K8117         C2013 05 11.26096 07 59 40.667+21 51 29.46         21.6 wL~0sDlF51')
Pandas(Index=104, obs80='K8117         C2013 05 11.26628 07 59 41.100+21 51 27.52         21.5 wL~0sDlF51')
Pandas(Index=105, obs80='K8117        5C2014 04 27.11736 14 06 26.75 -23 08 03.7          19.7 VL~2DWcW84')
Pandas(Index=106, obs80='K8117        5C2014 04 27.12386 14 06 26.37 -23 08 02.2                L~2DWcW84')
Pandas(Index=107, obs80='K8117        5C2014 04 27.12709 14 06 26.19 -23 08 01.6                L~2DWcW84')
Pandas(Index=108, obs80='K8117        5C2014 04 27.13034 14 06 26.00 -23 08 00.9                L~2DWcW84')
Pandas(Index=109, obs80='K8117         C2014 04 29.40094 14 04 18.655-22 59 36.14         19.9 wL~13x8F51')
Pandas(Index=110, obs80='K8117         C2014 04 29.41154 14 04 18.040-22 59 33.70         19.9 wL~13x8F51')
Pandas(Index=111, obs80='K8117         C2014 04 29.42212 14 04 17.427-22 59 31.22         20.0 wL~13x8F51')
Pandas(Index=112, obs80='K8117         C2014 04 29.43271 14 04 16.815-22 59 28.77         19.8 wL~13x8F51')
Pandas(Index=113, obs80='K8117         C2014 05 02.28856 14 01 39.09 -22 48 05.0          19.8 Vq~13x8G96')
Pandas(Index=114, obs80='K8117         C2014 05 02.29512 14 01 38.68 -22 48 03.3          19.2 Vq~13x8G96')
Pandas(Index=115, obs80='K8117         C2014 05 02.30167 14 01 38.37 -22 48 02.3          19.4 Vq~13x8G96')
Pandas(Index=116, obs80='K8117         C2014 05 02.30823 14 01 37.96 -22 48 00.8          19.2 Vq~13x8G96')
Pandas(Index=117, obs80='K8117         C2014 06 01.32171 13 41 45.968-20 35 27.61         20.5 wL~15HDF51')
Pandas(Index=118, obs80='K8117         C2014 06 01.33359 13 41 45.687-20 35 24.68         20.8 wL~15HDF51')
Pandas(Index=119, obs80='K8117         C2015 07 14.48322 21 49 14.724-16 18 31.26         20.5 wL~1UXlF51')
Pandas(Index=120, obs80='K8117         C2015 07 14.49440 21 49 14.339-16 18 32.32         20.5 wL~1UXlF51')
Pandas(Index=121, obs80='K8117         C2015 07 14.50559 21 49 13.937-16 18 33.10         20.5 wL~1UXlF51')
Pandas(Index=122, obs80='K8117         C2015 07 14.51677 21 49 13.556-16 18 34.13         20.5 wL~1UXlF51')
Pandas(Index=123, obs80='K8117         C2015 07 18.50980 21 46 48.980-16 24 28.39         20.3 wL~1UwNF51')
Pandas(Index=124, obs80='K8117         C2015 07 18.52084 21 46 48.511-16 24 29.38         20.5 wL~1UwNF51')
Pandas(Index=125, obs80='K8117         C2015 07 18.53220 21 46 48.055-16 24 30.41         20.5 wL~1UwNF51')
Pandas(Index=126, obs80='K8117         C2015 07 18.54340 21 46 47.600-16 24 31.65         20.4 wL~1UwNF51')
Pandas(Index=127, obs80='K8117         C2015 08 10.42173 21 27 52.380-17 10 10.83         19.8 wL~1VqYF51')
Pandas(Index=128, obs80='K8117         C2015 08 10.43273 21 27 51.742-17 10 12.18         20.0 wL~1VqYF51')
Pandas(Index=129, obs80='K8117         C2015 08 10.44375 21 27 51.099-17 10 13.52         19.9 wL~1VqYF51')
Pandas(Index=130, obs80='K8117         C2015 08 10.45478 21 27 50.459-17 10 14.87         19.8 wL~1VqYF51')
Pandas(Index=131, obs80='K8117         C2015 08 11.42441 21 26 56.029-17 12 11.73         20.0 wL~1VqYF51')
Pandas(Index=132, obs80='K8117         C2015 08 11.43580 21 26 55.359-17 12 13.04         20.0 wL~1VqYF51')
Pandas(Index=133, obs80='K8117         C2015 08 11.44718 21 26 54.699-17 12 14.46         19.9 wL~1VqYF51')
Pandas(Index=134, obs80='K8117         C2015 08 11.45861 21 26 54.032-17 12 15.81         19.9 wL~1VqYF51')
Pandas(Index=135, obs80='K8117         C2015 08 14.28655 21 24 15.00 -17 17 45.5          20.8 rR~1WOyG45')
Pandas(Index=136, obs80='K8117         C2015 08 14.29161 21 24 14.66 -17 17 46.2          20.5 rR~1WOyG45')
Pandas(Index=137, obs80='K8117         C2015 08 14.29673 21 24 14.40 -17 17 46.3          19.9 rR~1WOyG45')
Pandas(Index=138, obs80='K8117         C2015 08 14.30313 21 24 14.02 -17 17 47.8          20.0 rR~1WOyG45')
Pandas(Index=139, obs80='K8117         C2015 10 09.22722 20 57 43.419-17 00 38.16         21.0 wL~1YONF51')
Pandas(Index=140, obs80='K8117         C2015 10 09.23888 20 57 43.541-17 00 36.09         20.8 wL~1YONF51')
Pandas(Index=141, obs80='K8117         C2015 10 09.26225 20 57 43.769-17 00 32.38         21.1 wL~1YONF51')
Pandas(Index=142, obs80='K8117         C2015 10 10.24138 20 57 56.063-16 57 49.36         20.9 wL~1ZRGF51')
Pandas(Index=143, obs80='K8117         C2015 10 10.25306 20 57 56.188-16 57 47.40         21.2 wL~1ZRGF51')
Pandas(Index=144, obs80='K8117         C2015 10 10.26474 20 57 56.337-16 57 45.48         21.4 wL~1ZRGF51')
Pandas(Index=145, obs80='K8117         C2016 09 10.41101 04 14 08.25 +28 49 25.1          21.1 Vq~1y6iG96')
Pandas(Index=146, obs80='K8117         C2016 09 10.42828 04 14 09.02 +28 49 29.7                q~1y6iG96')
Pandas(Index=147, obs80='K8117         C2016 09 10.45010 04 14 09.81 +28 49 35.8                q~1y6iG96')
Pandas(Index=148, obs80='K8117         C2016 09 10.45698 04 14 10.11 +28 49 37.7                q~1y6iG96')
Pandas(Index=149, obs80='K8117         C2016 10 23.45473 04 18 20.26 +31 14 37.7          20.2 Vq~20bjG96')
Pandas(Index=150, obs80='K8117         C2016 10 23.46055 04 18 20.06 +31 14 38.3          20.6 Vq~20bjG96')
Pandas(Index=151, obs80='K8117         C2016 10 23.46506 04 18 19.90 +31 14 38.7          20.3 Vq~20bjG96')
Pandas(Index=152, obs80='K8117         C2016 10 23.47087 04 18 19.71 +31 14 39.1          20.8 Vq~20bjG96')
Pandas(Index=153, obs80='K8117         C2016 11 18.46258 03 56 21.20 +31 07 01.7          19.9 Vo~22dF691')
Pandas(Index=154, obs80='K8117         C2016 11 18.47203 03 56 20.59 +31 07 00.1          20.1 Vo~22dF691')
Pandas(Index=155, obs80='K8117         C2016 11 18.48150 03 56 20.02 +31 06 58.3          20.0 Vo~22dF691')
Pandas(Index=156, obs80='K8117         C2016 11 28.48797 03 45 52.269+30 36 35.77         20.0 wL~23DcF51')
Pandas(Index=157, obs80='K8117         C2016 11 28.49980 03 45 51.509+30 36 33.09         19.9 wL~23DcF51')
Pandas(Index=158, obs80='K8117         C2016 11 28.51173 03 45 50.754+30 36 30.32         19.9 wL~23DcF51')
Pandas(Index=159, obs80='K8117         C2016 11 28.52356 03 45 50.008+30 36 27.58         19.9 wL~23DcF51')
Pandas(Index=160, obs80='K8117         C2016 12 04.14919 03 40 15.27 +30 13 56.1          20.4 rR~23nBG45')
Pandas(Index=161, obs80='K8117         C2016 12 04.15432 03 40 14.97 +30 13 54.9          20.1 rR~23nBG45')
Pandas(Index=162, obs80='K8117         C2016 12 04.16481 03 40 14.29 +30 13 52.3          20.3 rR~23nBG45')
Pandas(Index=163, obs80='K8117         C2016 12 04.17014 03 40 13.98 +30 13 50.8          20.3 rR~23nBG45')
Pandas(Index=164, obs80='K8117         C2016 12 04.17571 03 40 13.68 +30 13 49.2          20.4 rR~23nBG45')
Pandas(Index=165, obs80='K8117         C2016 12 06.12274 03 38 24.20 +30 05 21.7          20.2 rR~23nBG45')
Pandas(Index=166, obs80='K8117         C2016 12 06.12800 03 38 23.91 +30 05 20.4          20.2 rR~23nBG45')
Pandas(Index=167, obs80='K8117         C2016 12 06.13296 03 38 23.62 +30 05 19.0          20.2 rR~23nBG45')
Pandas(Index=168, obs80='K8117         C2016 12 06.13826 03 38 23.24 +30 05 18.1          19.7 rR~23nBG45')
Pandas(Index=169, obs80='K8117         C2016 12 06.14309 03 38 23.04 +30 05 16.1          20.2 rR~23nBG45')
Pandas(Index=170, obs80='K8117         C2016 12 06.32156 03 38 12.88 +30 04 29.0          20.0 Vq~23nBG96')
Pandas(Index=171, obs80='K8117         C2016 12 06.33071 03 38 12.40 +30 04 26.7          20.5 Vq~23nBG96')
Pandas(Index=172, obs80='K8117         C2016 12 06.33664 03 38 12.03 +30 04 25.3          20.3 Vq~23nBG96')
Pandas(Index=173, obs80='K8117         C2016 12 06.34108 03 38 11.76 +30 04 23.9          20.4 Vq~23nBG96')
Pandas(Index=174, obs80='K8117         C2016 12 18.07711 03 28 57.32 +29 09 31.3          19.9 Vq~24OaG96')
Pandas(Index=175, obs80='K8117         C2016 12 18.08143 03 28 57.16 +29 09 30.1          20.0 Vq~24OaG96')
Pandas(Index=176, obs80='K8117         C2016 12 18.08575 03 28 57.04 +29 09 29.4          19.6 Vq~24OaG96')
Pandas(Index=177, obs80='K8117         C2016 12 18.09003 03 28 56.86 +29 09 27.9          20.1 Vq~24OaG96')
Pandas(Index=178, obs80='K8117         C2016 12 30.18671 03 23 18.83 +28 14 03.4          20.5 Vq~24rkG96')
Pandas(Index=179, obs80='K8117         C2016 12 30.19304 03 23 18.75 +28 14 02.0          20.4 Vq~24rkG96')
Pandas(Index=180, obs80='K8117         C2016 12 30.19733 03 23 18.66 +28 14 00.8          20.7 Vq~24rkG96')
Pandas(Index=181, obs80='K8117         C2016 12 30.20161 03 23 18.60 +28 13 59.4          20.3 Vq~24rkG96')
Pandas(Index=182, obs80='K8117         C2017 12 20.48421 11 36 51.02 +02 09 40.1          20.9 GU~2TjVG96')
Pandas(Index=183, obs80='K8117         C2017 12 20.49502 11 36 51.41 +02 09 36.8          21.3 GU~2TjVG96')
Pandas(Index=184, obs80='K8117         C2017 12 20.50018 11 36 51.61 +02 09 34.4                U~2TjVG96')
Pandas(Index=185, obs80='K8117         C2017 12 20.50532 11 36 51.83 +02 09 32.3          21.6 GU~2TjVG96')