# MPCHandler

In [1]:
from spacerocks import MPCHandler
from spacerocks import SpiceKernel
import pandas as pd

kernel = SpiceKernel.defaults()

Using default configuration:
  Kernel paths: ["/Users/thomasruch/.spacerocks/spice"]
  Download directory: "/Users/thomasruch/.spacerocks/spice"
  Auto-download: true

Processing kernel: latest_leapseconds.tls
✓ Found existing kernel at: /Users/thomasruch/.spacerocks/spice/latest_leapseconds.tls
Loading kernel: /Users/thomasruch/.spacerocks/spice/latest_leapseconds.tls

Processing kernel: de440s.bsp
✓ Found existing kernel at: /Users/thomasruch/.spacerocks/spice/de440s.bsp
Loading kernel: /Users/thomasruch/.spacerocks/spice/de440s.bsp

Processing kernel: earth_1962_240827_2124_combined.bpc
✓ Found existing kernel at: /Users/thomasruch/.spacerocks/spice/earth_1962_240827_2124_combined.bpc
Loading kernel: /Users/thomasruch/.spacerocks/spice/earth_1962_240827_2124_combined.bpc

Processing kernel: codes_300ast_20100725.bsp
✓ Found existing kernel at: /Users/thomasruch/.spacerocks/spice/codes_300ast_20100725.bsp
Loading kernel: /Users/thomasruch/.spacerocks/spice/codes_300ast_20100725.bsp

Processing kernel: codes_300ast_20100725.tf
✓ Found existing kernel at: /Users/thomasruch/.spacerocks/spice/codes_300ast_20100725.tf
Loading kernel: /Users/thomasruch/.spacerocks/spice/codes_300ast_20100725.tf

In [2]:
# Create a new MPCHandler object and pass the path to the data directory where the MPC data files are stored
# The path can be specified as shown below, or if left blank, it will default to and make "~/.spacerocks/mpc" in your home directory
"""
mpc_data_path = "data/mpc"
handler = MPCHandler(mpc_data_path)
"""

handler = MPCHandler()

In [3]:
# Create a dataframe of all the Near-Earth Asteroids (NEAs) from the MPC data files
nea_df = handler.fetch_data(
    catalog="nea_extended", # https://minorplanetcenter.net/data details available catalogs
    orbit_type=None,  # None means get all types, and is the default
    storage_format="json",  # Options: "feather", "json", None: Default is "feather", None will get the data directly from the MPC without saving it locally
    output_format="dataframe" # Options: "dataframe", "rocks": Default is "dataframe", "rocks" returns a RockCollection 
)

# Available orbit_types:

# "Atira",
# "Aten", 
# "Apollo",
# "Amor",
# "Hungaria",
# "MBA",
# "Phocaea",
# "Hilda",
# "Jupiter Trojan",
# "Distant Object"

Using existing json file: /Users/thomasruch/.spacerocks/mpc/nea_extended.json.gz

In [4]:
nea_df.head()

,H,G,Epoch,M,Peri,Node,i,e,a,Principal_desig,orbit_type
0,10.41,0.15,2460600.5,86.66754,178.91030,304.27434,10.82773,0.222691,1.458181,A898 PA,Amor
1,15.59,0.15,2460600.5,148.45068,156.21553,183.85715,11.57526,0.546779,2.636157,A911 TB,Amor
2,13.79,0.15,2460600.5,340.19843,350.47424,110.42302,9.39880,0.571093,2.472525,A918 AA,Amor
3,9.18,0.15,2460600.5,6.98496,132.49616,215.49497,26.68673,0.532826,2.665299,A924 UB,Amor
4,17.37,0.15,2460600.5,271.70081,26.71763,171.26079,11.86849,0.434718,1.920154,1932 EA1,Amor

In [5]:
# Make a dataframe of all the Jupiter Trojans in the MPC and save it as a json 
jt_df = handler.fetch_data(
    catalog="mpcorb_extended",
    orbit_type="Jupiter Trojan",
    storage_format="json")

Using existing json file: /Users/thomasruch/.spacerocks/mpc/mpcorb_extended.json.gz

In [6]:
jt_df.head()

,H,G,Epoch,M,Peri,Node,i,e,a,Principal_desig,orbit_type
0,8.25,0.15,2460600.5,43.90867,133.98436,316.53930,10.31751,0.148450,5.212198,A906 DN,Jupiter Trojan
1,8.25,0.15,2460600.5,9.05119,308.59117,44.35145,22.06381,0.139696,5.206645,A906 UL,Jupiter Trojan
2,7.36,0.15,2460600.5,337.57832,179.74876,342.80146,18.15128,0.023911,5.274477,A907 CF,Jupiter Trojan
3,8.73,0.15,2460600.5,148.86038,343.97657,350.75593,4.52196,0.115835,5.169928,A908 FE,Jupiter Trojan
4,8.64,0.15,2460600.5,96.38488,337.47229,301.45814,8.89552,0.124572,5.207680,A917 SU,Jupiter Trojan

In [7]:
# Now if we want to access the 'mpcorb_extended' catalog again, it will search for the file 
# and load it from there, instead of downloading it again from the MPC

apollo_df = handler.fetch_data(
    catalog="mpcorb_extended",
    orbit_type="Apollo")

Using existing json file: /Users/thomasruch/.spacerocks/mpc/mpcorb_extended.json.gz

In [8]:
apollo_df.head()

,H,G,Epoch,M,Peri,Node,i,e,a,Principal_desig,orbit_type
0,16.55,0.15,2460400.5,344.75531,31.43692,87.95325,22.80165,0.826921,1.078088,1949 MA,Apollo
1,15.27,0.15,2460600.5,289.35927,277.00695,337.14978,13.33591,0.335622,1.245628,1951 RA,Apollo
2,14.28,0.15,2460600.5,196.26473,127.27204,274.20996,9.38162,0.436080,1.367918,1948 OA,Apollo
3,16.08,0.09,2460600.5,252.86869,286.03295,35.55651,6.35246,0.559872,1.470612,1932 HA,Apollo
4,15.46,0.15,2460600.5,173.83076,268.56970,345.99703,18.34949,0.606271,2.261465,1948 EA,Apollo

In [9]:
# We can also get the data in the form of a RockCollection object, either by passing the output_format parameter as "rocks" or by using the RockCollection class
from spacerocks import RockCollection

nea_rocks = RockCollection.from_mpc(
    catalog="nea_extended",
    download_data=False, # Set to True if you want to download the data from the MPC, default is False
    orbit_type=None, # None means get all types, and is the default 
)

trojan_rocks = handler.fetch_data(
    catalog="mpcorb_extended",
    orbit_type="Jupiter Trojan",
    output_format="rocks")

Using existing json file: /Users/thomasruch/.spacerocks/mpc/nea_extended.json.gz
Using existing json file: /Users/thomasruch/.spacerocks/mpc/mpcorb_extended.json.gz

In [10]:
nea_rocks

RockCollection: 37398 rocks

In [11]:
nea_rocks[0]

SpaceRock: A898 PA
position: [[-0.847254164498476, -1.2219158379054114, -0.2655208256624848]]
velocity: [[0.009213129392774662, -0.010204668116499577, 0.00035698153637254363]]
epoch: 2460600.5 UTC JD
reference_plane: ECLIPJ2000
origin: SSB

In [12]:
print(nea_rocks[0].name)
print(nea_rocks[0].a())
print(nea_rocks[0].e())
print(nea_rocks[0].inc())
print(nea_rocks[0].node())
print(nea_rocks[0].arg())
print(nea_rocks[0].mean_anomaly())

A898 PA
1.4581813
0.22269060000000004
0.18897953901696607
5.310589062332683
3.122573800730802
1.512633927603887

In [13]:
trojan_rocks[0]

SpaceRock: A906 DN
position: [[-3.988246675742351, 2.518282639855654, -0.16665568663841815]]
velocity: [[-0.005090352346548766, -0.0063728118511861154, -0.0014795131793110638]]
epoch: 2460600.5 UTC JD
reference_plane: ECLIPJ2000
origin: SSB

In [14]:
# You can also get all the detection data from the MPC for a specific object by passing its name with get_detections and the format(s) you want the data in 
# (ADES is the current MPC standard and default. Options are "ADES_DF", "OBS_DF", "XML".)

# If ADES is specified, get_detections will return a tuple with Observation objects and the raw data in the specified format(s)
observations, response = handler.get_detections("davidgerdes", formats=["ADES_DF", "OBS_DF", "XML"])
if response:
    ades_df = pd.DataFrame(response[0]['ADES_DF'])
    obs_df = pd.DataFrame(response[0]['OBS_DF'])
    xml_string = response[0]['XML']

In [15]:
ades_df

,Obstype,artsat,astcat,band,com,ctr,dec,decstar,delay,deltadec,...,rmstime,seeing,stn,subfmt,subfrm,sys,trkid,trksub,trx,unctime
0,optical,None,UNK,R,None,None,13.48519,None,None,None,...,None,None,695,M92,None,None,000003o-bf,MB5190,None,None
1,optical,None,UNK,None,None,None,13.49061,None,None,None,...,None,None,695,M92,None,None,000003o-bf,MB5190,None,None
2,optical,None,USNOSA1,V,None,None,13.80372,None,None,None,...,None,None,691,M92,None,None,000003G-LH,A2E41j,None,None
3,optical,None,USNOSA1,V,None,None,13.80467,None,None,None,...,None,None,691,M92,None,None,000003G-LH,A2E41j,None,None
4,optical,None,USNOSA1,V,None,None,13.80550,None,None,None,...,None,None,691,M92,None,None,000003G-LH,A2E41j,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,optical,None,Gaia3E,Pw,None,None,-12.269759,None,None,None,...,None,None,F51,A17,None,None,00000IHUaX,P1201GQ,None,None
411,optical,None,Gaia2,G,None,None,-6.138830,None,None,None,...,None,None,V00,A17,None,None,00000IV6GU,C0Z6PW5,None,None
412,optical,None,Gaia2,G,None,None,-6.138260,None,None,None,...,None,None,V00,A17,None,None,00000IV6GU,C0Z6PW5,None,None
413,optical,None,Gaia2,G,None,None,-6.137480,None,None,None,...,None,None,V00,A17,None,None,00000IV6GU,C0Z6PW5,None,None
414,optical,None,Gaia2,G,None,None,-6.136740,None,None,None,...,None,None,V00,A17,None,None,00000IV6GU,C0Z6PW5,None,None

In [16]:
observations[0]

Observation:
(RA=150.0820°, Dec=13.4852°)
mag: 19.40
epoch: 2451580.8331597224 UTC JD